### ISSUE TITLE
TrocoInterator	linha 72

### ISSUE THREAD

**Issue by ubrals** [PaulaGM/Source-Code-Inspection#17]
Classe: TrocoInterator
Linhas: 72
Descrição:  Loop for está ocorrendo de forma incorreta. Contando 7 vezes ao invés de 6. A var.iavel i deve ser inicializada com 5.  
Categoria: Controle 
Severidade: Baixo

**Comment by PaulaGM** [comment]
for (int i = 5; i >= 0 && ret != null; i++) {
