### ISSUE TITLE
2.5	Diagrama de Seqüência – Solicitar troco

### ISSUE THREAD

**Issue by ubrals** [PaulaGM/Source-Code-Inspection#26]
Tipo de Defeito: Omissão

Seriedade: médio

Observação: O Sistema não zera o valor do saldo.

**Comment by PaulaGM** [comment]
Entre o retorno "1.1.3: getIterator" e o retorno "1.2: getTroco" deve zerar o valor do saldo com um auto-estímulo "zerarSaldo"
