### ISSUE TITLE
2.5	Diagrama de Seqüência – Solicitar troco

### ISSUE THREAD

**Issue by ubrals** [PaulaGM/Source-Code-Inspection#27]
Tipo de Defeito: Omissão

Seriedade: Médio

Observação: O Sistema não verifica o saldo e devolve a quantidade do saldo em notas de papel-moeda.

**Comment by PaulaGM** [comment]
Entre o estímulo "1.1: getTroco" e a criação "1.1.1: Troco" deve ser validado com auto-estímulo "getSaldo" para fazer a criação "1.1.1: Troco" com o valor correto.
